import { NextResponse } from "next/server";
import { getDb, getSessionUser } from "../../../lib/db";
import {
  getRepo,
  getBranchSha,
  ensureFork,
  createBranch,
  createOrUpdateFile,
  createPullRequest,
} from "../../../lib/github";

export async function POST(request) {
  const user = await getSessionUser(request);
  if (!user) {
    return NextResponse.json({ error: "Not signed in" }, { status: 401 });
  }

  const { owner, repo, issueNumber, title, body, filePath, fileContent } = await request.json();
  if (!owner || !repo || !issueNumber) {
    return NextResponse.json({ error: "owner, repo, and issueNumber are required" }, { status: 400 });
  }

  const db = getDb();

  try {
    // 1. Fetch upstream repository metadata to inspect default branch & write permissions
    const upstreamRepo = await getRepo(user.access_token, owner, repo);
    const defaultBranch = upstreamRepo.default_branch || "main";
    const hasDirectPush = Boolean(upstreamRepo.permissions?.push);

    // Save/update the default_branch in DB cache if repo exists in DB
    try {
      await db.query(
        `UPDATE repositories SET default_branch = $1 WHERE owner = $2 AND name = $3`,
        [defaultBranch, owner, repo]
      );
    } catch {
      // Non-fatal if DB update fails
    }

    // Determine target push repository (direct push vs fork)
    const isDirectPush = hasDirectPush || owner.toLowerCase() === user.github_login.toLowerCase();
    let pushOwner = owner;

    if (!isDirectPush) {
      // Ensure the user has an accessible fork of this upstream repository
      await ensureFork(user.access_token, owner, repo, user.github_login);
      pushOwner = user.github_login;
    }

    // 2. Obtain latest commit SHA from upstream default branch
    const baseSha = await getBranchSha(user.access_token, owner, repo, defaultBranch);

    // 3. Create a dedicated branch on the target push repository (fork or direct)
    const branchName = `codesphere/fix-issue-${issueNumber}-${Date.now().toString().slice(-4)}`;
    await createBranch(user.access_token, pushOwner, repo, branchName, baseSha);

    // 4. Ensure at least one commit exists on the branch.
    // GitHub rejects PR creation with 422 ("No commits between base and head") if the branch has 0 diff.
    if (filePath && fileContent) {
      await createOrUpdateFile(
        user.access_token,
        pushOwner,
        repo,
        filePath,
        fileContent,
        `fix: apply resolution for issue #${issueNumber}`,
        branchName
      );
    } else {
      // Fallback: commit structured fix resolution document so the branch contains changes and a documented fix
      const resolutionDoc = `# Proposed Fix for Issue #${issueNumber}\n\n${body || "Proposed resolution generated by CodeSphere AI."}\n\n---\n*Formulated by @${user.github_login} via CodeSphere AI*`;
      await createOrUpdateFile(
        user.access_token,
        pushOwner,
        repo,
        `.codesphere/fixes/issue-${issueNumber}.md`,
        resolutionDoc,
        `fix: propose solution for issue #${issueNumber}`,
        branchName
      );
    }

    // 5. Open the Pull Request on the upstream repository
    const prTitle = title || `fix: address issue #${issueNumber}`;
    const prBody = `${body || "Proposed fix generated via CodeSphere AI."}\n\nFixes #${issueNumber}\n\n---\n_Formulated and opened via CodeSphere AI by @${user.github_login}_`;

    // For cross-repository (fork) PRs, head must be namespaced: 'username:branch'
    const headRef = isDirectPush ? branchName : `${pushOwner}:${branchName}`;

    const pr = await createPullRequest(
      user.access_token,
      owner,
      repo,
      prTitle,
      prBody,
      headRef,
      defaultBranch
    );

    return NextResponse.json({
      ok: true,
      url: pr.html_url,
      number: pr.number,
      branch: branchName,
      isFork: !isDirectPush,
      forkOwner: !isDirectPush ? pushOwner : null,
    });
  } catch (err) {
    console.error("Create PR failed:", err);
    let message = err.message || "Failed to create Pull Request";
    if (message.includes("403") || message.includes("Resource not accessible by integration")) {
      message = "GitHub permission error: token lacks required permissions. Please re-authenticate with repo access.";
    }
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
